module.exports = {
  CHAT_ROOMS: "CHAT_ROOMS",
  JOIN_ROOM: "JOIN_ROOM",
//  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
//  MESSAGE_SENT: "MESSAGE_SENT",
//  USER_DISCONNECTED: "USER_DISCONNECTED",
//  TYPING: "TYPING",
//  VERIFY_USER: "VERIFY_USER",
//  LOGOUT: "LOGOUT",
  SEND_MESSAGE: "SEND_MESSAGE",
//  ADD_USER: "ADD_USER",
  USERS_LIST: "USERS_LIST",
  LOGIN: "LOGIN",
  USER_VERIFIED: "USER_VERIFIED",
  ERROR: "ERROR",
  ROOM_JOINED: "ROOM_JOINED",
  ROOM_DETAILS: "ROOM_DETAILS",
  CHAT_USER: "CHAT_USER",
  CHAT_STARTED: "CHAT_STARTED",
//  USER_MESSAEG_RECEIVED: "USER_MESSAEG_RECEIVED"
};

