module.exports = {
  CHAT_ROOMS: "CHAT_ROOMS",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  USERS_LIST: "USERS_LIST",
  USER_VERIFIED: "USER_VERIFIED",
  ERROR: "ERROR",
  ROOM_JOINED: "ROOM_JOINED",
  CHAT_STARTED: "CHAT_STARTED",
    DISCONNECT: "disconnect",
    LOGIN: "LOGIN",
    SEND_MESSAGE: "SEND_MESSAGE",
    JOIN_ROOM: "JOIN_ROOM",
    CHAT_USER: "CHAT_USER"
    
};
